### ISSUE TITLE
Need high-level test

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#1003]
We need some extra higher automated tests to prevent from regressions as we've seen for the last days.
* Import a project with various sources (we can put anything we have in mind here)
* Build and verify it has no errors, or only expected errors (covers the build)
* Opens every file in the editor, verify editors open fine (covers the Javac->DOM translation)
* From the DOM, navigate the tree and call all possible `resolveBindings` (covers JavacBindingResolver)

**Comment by datho7561** [comment]
> Build and verify it has no errors, or only expected errors (covers the build)

#1017 covers this, if someone needs to make another similar test in the future, feel free to refer to it

**Comment by mickaelistria** [comment]
While I still think the even bigger tests would be profitable, I hardly imagine anyone spending time to write such a test at the moment. I hope that if we add new tests for each new strange case we identify that's not already covered, we'll end up having a good enough coverage.
So I'm closing it; but if anyone wants to design a really powerful acceptance test scenario, that would still be very welcome.
