### ISSUE TITLE
Errenous `new` statement not recovered optimally

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#1037]
Inspired from CompletionContextTest.test0112
```java
public class X {
  Object o = new 
}
```
is recovered as
```java
public class X {
  Object o = $missing$;
}
```
while the input from Javac would allow to convert it to
```java
public class X {
  Object o = new $missing$();
}
```

**Comment by robstryker** [comment]
Fixed by https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/1040 and other commits that helped.
