### ISSUE TITLE
[Javac] complete diagnostics -> problems mapping

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#14]
We need to complete the logic that maps Javac diagnostics to JDT problems, in order to enable proper messages and quick-fixes for compiler problems.

**Comment by fbricon** [comment]
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/290 is a first step towards problem mapping

**Comment by mickaelistria** [comment]
A 2nd step actually, some mapping was already existing before.

**Comment by testforstephen** [comment]
In the UI, I plan to display the original Javac code directly within the Problems view. And then our focus is on mapping those diagnostics with quick fixes supported to JDT problem ids, and ensure that the quick fixes can appear on the associated problems.

![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/14052197/264f3321-24e1-4522-a2e6-e4de11d0be86)

**Comment by mickaelistria** [comment]
I think we're mostly done and don't need this "epic" any more. Particular reports are now more actionable.
