### ISSUE TITLE
Failures related to recovery

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#143]
Let's list tests that are failing because of recovery (the list grows as we investigate tests)

* org.eclipse.jdt.core.tests.dom.ASTConverterTestAST3_2.test0697
* org.eclipse.jdt.core.tests.dom.ASTConverterTestAST4_2.test0697
* org.eclipse.jdt.core.tests.dom.ASTConverterTestAST8_2.test0697
* org.eclipse.jdt.core.tests.dom.ASTModelBridgeTests.testMethod10
* org.eclipse.jdt.core.tests.model.HierarchyOnWorkingCopiesTests.test400905a
* org.eclipse.jdt.core.tests.model.LocalElementTests.testLocalType5
* org.eclipse.jdt.core.tests.model.TypeResolveTests.testBug533884c_blockless(TypeResolveTests.java:1609)
* HierarchyOnWorkingCopiesTest.test400905a

Not exactly the same kind of recovery, but still something that JDT can do better

* ResolveTests12To15.test007 fails at creating a binding for the "parameters" of an erroneous case statement "action" while both should be decorelated enough for the binding to still resolve. The SelectionParser implements a SearchBased workaround for that.

**Comment by datho7561** [comment]
- ResolveTests1_5.testBrokenSwitch0, ResolveTests1_5.testBrokenSwitch1: we can probably get these tests to work with javac but they don't pass with ECJ. Statement recovery in classes nested under methods is really bad in ECJ, unless you use the hacks introduced by CompletionParser, and those hacks are hard to port to the base parser class
- ResolveTests12to15.test007 is also related to switch recovery

**Comment by mickaelistria** [comment]
Ongoing PR to capture that: https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/178

**Comment by mickaelistria** [comment]
We won't work further on making JDT's DOM-first approach fully compatible with ECJ. It would still be a nice-to-have, but the remaining issues are hard to fix in ECJ and are not a requirement to enable alternative compiler backends, so no further work in planned on this topic.
DOM-first is now fully included with DOM with Javac branch.
Let's close.
If anyone still believes this DOM-first work makes sense independently of Javac, please start the discussion and we'd be happy to support anyone willing to consolidate DOM-first with ECJ.
