### ISSUE TITLE
[DOM-first] Tests we probably won't fix

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#159]
Here is a list of tests that seem of very low value, or even wrong, to make work with DOM-first, and that we should probably consider just ignoring:

* JavaSearchBugs8Tests.test430159c/test430159c -> test that codeSelect on `::` does *not* jump to the actual method definition
* IgnoreOptionalProblemsFromSourceFoldersTests.* (5 tests) are actually testing lower-level compiler behavior about "ProblemSeverities.Optional", but this optional flag seems entirely lost when moving to DOM-land. The case for those problems seem relatively rare, and as our final goal is to behave like Javac anyway, it doesn't seem to map to an interesting concept of javac.

**Comment by datho7561** [comment]
- ResolveTests1_5.testBrokenSwitch0, ResolveTests1_5.testBrokenSwitch1: we can probably get these tests to work with javac but they don't pass with ECJ. Statement recovery in classes nested under methods is really bad in ECJ, unless you use the hacks introduced by CompletionParser, and those hacks are hard to port to the base parser class

**Comment by mickaelistria** [comment]
Instead of listing issues here, we will try to guard those tests by a system property.
Something like `assumeFalse("This test is currently not supported using DOM-first approach", CompilationUnit.DOM_BASED_OPERATIONS);`

**Comment by mickaelistria** [comment]
All fixed or ignored, remaining issues to adopt DOM-first with ECJ are tracked in https://github.com/orgs/eclipse-jdtls/projects/1
