### ISSUE TITLE
[DOM-first] Fix `JavaSearchTest.testEnum04`

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#17]
I'm looking into resolving the root cause of the test failure for `JavaSearchTest.testEnum04`

**Comment by datho7561** [comment]
Found the root cause of the NPE, but the tests are still failing. It seems like the search engine is not collecting the Java files.

**Comment by mickaelistria** [comment]
OK. Maybe you can have a look at the test failures from https://github.com/mickaelistria/eclipse.jdt.core/tree/test-with-dom , some other tests may exhibit the same NPE and those could be used to validate that the NPE is fixed, and make some of those tests pass.
In any case, if you think your fix is valid even if not enough to fix this test, please create a PR for it.
