### ISSUE TITLE
Support JDT Java project's compiler options in Javac compiler

### ISSUE THREAD

**Issue by testforstephen** [eclipse-jdtls/eclipse-jdt-core-incubator#214]
Map JDT compiler options (such as source, target, enable-preview, etc. ) to Javac compiler options.

**Comment by mickaelistria** [comment]
Isn't it fixed by https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/commit/364001ed0f2302b7821489354c4251df4dd07feb ?

**Comment by mickaelistria** [comment]
Let's close here as most options seems to be passed in already. If one sees some particular ones missing, please create a new ticket.
