### ISSUE TITLE
[javac] implement `JavacCompilationUnitResolver.resolve`

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#216]
This method is used in the `org.eclipse.jdt.core.tests.compiler` regressions test suite, so it would be nice to implement it to get those tests passing.

I'm interested in taking on this issue.

**Comment by datho7561** [comment]
The first main obstacle is building the bindings and returning the requested bindings to the callee through the visitor that's passed in. It should be possible to visit all the compilation units using an AST visitor and build all the bindings for the relevant nodes. However, maybe there is a smarter way to do this.

**Comment by mickaelistria** [comment]
@fbricon IIRC you're facing a failure because of the unimplemented method. Can you please share some steps to reproduce and/or a stacktrace?
