### ISSUE TITLE
[javac] Assign the appropriate build output path for each source root

### ISSUE THREAD

**Issue by testforstephen** [eclipse-jdtls/eclipse-jdt-core-incubator#222]
Take https://github.com/spring-projects/spring-petclinic for example, its source path structure as follows:

![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/14052197/b879a99e-a46b-4da1-adbb-d09100e577f8)

ECJ based Java builder result:
![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/14052197/ce8baa1b-2e4f-49c8-b622-57d3d7847272)

Javac based Java builder result, production and test classes are mixed together.
![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/14052197/0bc8a5dd-8767-4b68-89ac-72234939edaa)

**Comment by mickaelistria** [comment]
Note that the "compile with javac" story is well isolated from other bits. It could even be a standalone fragment per se if you think it'd be more convenient. Once matured enough, this particular bit could even may be hosted directly in JDT with some options "Generate classes with: Eclipse Compiler/built-in Javac (if compatible with source/target Java version)".

**Comment by testforstephen** [comment]
Good idea. If we consider allowing it to work in Eclipse, an alternative idea is to implement the javac builder using the javac command line directly instead of the compiler API. The compiler API requires us to run the server on the latest JDK, which may not be acceptable to Eclipse. Javac CLI doesn't have the limitation, thus offering more flexibility to utilize the javac from the user project's JDK.

**Comment by mickaelistria** [comment]
Yes, although calling javac CLI may reveal significantly slower than calling in-process API. But if we manage to have a switch to select between ECJ and alternative builders such Javac CLI in JDT, and then if later we think it's good to also provide the in-process Javac support, it will be easy to add it. So overall, whichever alternative implementations is implemented and integrated first, the work of just allowing an alternative implementation would bring huge value.

If you're interested in leading this effort, I would recommend that you open an issue about it to upstream JDT ASAP to present the proposal, and hopefully get the "strategy picker" code in.

**Comment by gayanper** [comment]
@mickaelistria I was looking into fixing this and I think I have a working solution, But I do see that my build folder `bin` in empty, that is not class files are generated ? I created a topic branch to work based on `dom-with-javac`, is that the correct branch to work on ?

**Comment by gayanper** [comment]
The build works fine with my fix for maven projects, but not for gradle. I might need to check a bit deep
