### ISSUE TITLE
[Javac] Javadoc not present when including some `@since` or other `@...` 

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#227]
Try this example
```java
/**
 * Javadoc blah blah
 * @since 1.0
 */
public class Blah {}
```
Hover on `Blah`.
Expected
```
Javadoc blah blah
**@since** 1.0
```
Got `@since 1.0`

**Comment by mickaelistria** [comment]
@robstryker this may a regression related to some of the recent change you've made.

**Comment by fbricon** [comment]
this one makes the UX pretty frustrating

**Comment by mickaelistria** [comment]
Let's close this one as the workaround does some good part of the job. But a proper and complete implementation is still necessary, this is tracked in #367
