### ISSUE TITLE
[javac] support converting string template nodes

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#269]
Create a simple class that uses string templates:

```java
package com.github.datho7561;

public class Main {
	public static void main(String[] args) {
		STR."asdf\{}";
	}
}
```

I see logs like this:

Caused by: java.lang.UnsupportedOperationException: Missing support to convert '[STR]"asdf\{}"(null)' of type JCStringTemplate

**Comment by mickaelistria** [comment]
Adding support for such new Java constructs should be made high priority over other issues as we're willing to demonstrate a faster adoption of new Java language features.

**Comment by akurtakov** [comment]
String template has been removed from java 23. Look in jdt core issues for details.

**Comment by mickaelistria** [comment]
> String template has been removed from java 23. Look in jdt core issues for details.

:tada:

**Comment by mickaelistria** [comment]
https://bugs.openjdk.org/browse/JDK-8329949

**Comment by mickaelistria** [comment]
Let's not care about supporting String templates then.

**Comment by mickaelistria** [comment]
I'm reopening this as I think it's still useful (and easy enough) for demo purpose.

**Comment by mickaelistria** [comment]
Let's close it again, as we can't use them with Java 23 anyway and we're now mainly targetting JAva 23.
