### ISSUE TITLE
[javac] Report "unused ..." diagnostics

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#300]
The javac compiler doesn't report "unused ..." diagnostics, but there's still a way to access that information, see how it's done in https://github.com/georgewfraser/java-language-server:  `com.sun.source.tree.CompilationUnitTree` is [scanned](https://github.com/georgewfraser/java-language-server/blob/ca503f1728594af4b77d68de0c04fd81d9dc10d1/src/main/java/org/javacs/markup/ErrorProvider.java#L49-L57) for unused local variables or fields in https://github.com/georgewfraser/java-language-server/blob/master/src/main/java/org/javacs/markup/WarnUnused.java

**Comment by mickaelistria** [comment]
We can probably just copy the code from the java-language-server, it's MIT and it can work almost without change.

**Comment by fbricon** [comment]
@testforstephen is this something you could look at?

**Comment by testforstephen** [comment]
Sure, I have made some local experiments to support unused local variables, private fields, methods, and classes, and it works. Basically, we need to add this support into two places: the JavacCompiler and the DOM parser, as both will report diagnostics.

**Comment by fbricon** [comment]
Sounds awesome, waiting for your PR ;-)
