### ISSUE TITLE
[javac] Errors in records are not reported

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#319]
JDT doesn't report any problem here (on any other errors):
```java
public record BadRecord(String foo) {
    what happens here?
}
```

**Comment by fbricon** [comment]
Something's fishy here, until the record class is opened, the errors are properly reported, but disappear as soon as it's opened:
![May-02-2024 12-36-58](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/148698/af0d50b9-03f2-4eef-98f5-b55768c43864)

**Comment by datho7561** [comment]
> Something's fishy here, until the record class is opened, the errors are properly reported, but disappear as soon as it's opened:

It could be the syntax server?

I was hoping Snjezana's PR would magically fix this, but instead there is a crash when trying to work with a class file with a broken record declaration. I'm taking a look into it.

**Comment by datho7561** [comment]
I've addressed the crash. The syntax highlighting is okay after the fix, but doesn't match ECJ exactly. In order to match ECJ, we will need to use the scanner to get the range of the token that's before the offset where the error is reported.
