### ISSUE TITLE
[javac] unexpected "incompatible types: int cannot be converted to int[]" error

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#320]
When opening https://github.com/openjdk/jdk/blob/fe23068d946181b0346e470d3172c5d29cc2e05c/test/langtools/tools/javac/diags/examples/ArrayDimMissing.java, i.e:

```java
class ArrayDimMissing {
    int[] array = new int[];
}
```

An  `incompatible types: int cannot be converted to int[]` error is reported unexpectedly, instead of just `array dimension missing`. 

<img width="783" alt="Screenshot 2024-05-02 at 14 55 24" src="https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/148698/41d6b002-295c-4f78-9080-9f393923a1f0">

JDT/ECJ only reports a single `Variable must provide either dimension expressions or an array initializer`, so it looks like a regression specific to the dom-with-javac branch

**Comment by mickaelistria** [comment]
I cannot reproduce this issue in Eclipse IDE, I only see the "array dimention missing".

**Comment by datho7561** [comment]
I can reproduce this issue in Eclipse IDE.

**Comment by datho7561** [comment]
On the command line, `javac` only generates one error

**Comment by datho7561** [comment]
I looked into the jdk code, and couldn't figure out where and how the error is being generated. I think that the bottom line is that the problem reporter is in charge of assuring two issues don't get reported at the same position. This means we will probably need to code such a mechanism.
