### ISSUE TITLE
[DOM-first] Fix `ASTModelBridgeTests.testMethod10`

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#34]
Fix the test when building the model with using the DOM.

The root cause is that the existing model builder (that uses `SourceElementParser`) successfully recovers the anonymous class in the following snippet, whereas the AST that `DOMToModelPopulator` gets doesn't.

```java
public class X {
        void test() {
                new Object() {
                        /*start*/public void yes() {
                                System.out.println("hello world");
                        }/*end*/
                } // missing semicolon
        }
}
```

**Comment by datho7561** [comment]
After a bit more investigation, I figured out that `SourceElementParser` successfully adds the anonymous class to the model, but it doesn't recover the AST node.

It uses a visitor pattern to create information about the anonymous class, by overriding the method that creates the anonymous class node. Since the parser uses a bottom-up technique, it will create an anonymous class even if the surrounding context means that the anonymous class is invalid (in this case due to the missing semicolon). However, the parser cannot parse the method body, so there is no AST for the method body.

**Comment by mickaelistria** [comment]
This was fixed a long-ish time ago (can't fine the commit).
