### ISSUE TITLE
[javac] first letter of type is colour as a parameter name for primitive types

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#379]
![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/22376627/7da84603-4a8b-41e1-863b-8971f4908bb5)

Note the `i` in `int` and the `d` in `double`

This doesn't happen for non-primitive types such as `String`

**Comment by mickaelistria** [comment]
I cannot reproduce this issue with current HEAD. Can you please verify and provide details?

**Comment by datho7561** [comment]
![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/22376627/89097af7-094c-4481-aaf3-7de22e6b19f5)

I still get it, but it's not consistent which characters are different and sometimes it works as expected.

**Comment by datho7561** [comment]
Actually, I figured out what's happening: if the primitive type contains the parameter name, then that portion of the primitive is highlighted as if its the parameter's name.

**Comment by datho7561** [comment]
![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/22376627/4b9bc0f5-0e68-4585-b220-fd88b05a54fd)

Note: `long lon`, the `l`, `o`, and `n` from `long` are highlighted as if they are the parameter name
