### ISSUE TITLE
Microsoft IntelliCode extension causing issues with javac based WIP completions

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdtls/eclipse-jdt-core-incubator#384]
```
lass org.eclipse.jdt.internal.codeassist.DOMCompletionContext cannot be cast to class org.eclipse.jdt.internal.codeassist.InternalCompletionContext (org.eclipse.jdt.internal.codeassist.DOMCompletionContext and org.eclipse.jdt.internal.codeassist.InternalCompletionContext are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @17078d37)
java.lang.ClassCastException: class org.eclipse.jdt.internal.codeassist.DOMCompletionContext cannot be cast to class org.eclipse.jdt.internal.codeassist.InternalCompletionContext (org.eclipse.jdt.internal.codeassist.DOMCompletionContext and org.eclipse.jdt.internal.codeassist.InternalCompletionContext are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @17078d37)
	at com.microsoft.jdtls.intellicode.core.ModelBasedRankingProvider.rank(ModelBasedRankingProvider.java:52)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getAggregatedRankingResult(CompletionProposalRequestor.java:363)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:262)
```

@jdneo @testforstephen can you check if this can be resolved from the intellicode extension side with that team in away the extension will work either with or without javac changes.

**Comment by mickaelistria** [comment]
~Wouldn't it be possible/better to make DOMCompletionContext implement InternalCompletionContext ?~

**Comment by mickaelistria** [comment]
Please ignore previous comment, this wouldn't fit as InternalCompletionContext only adds ECJ specific methods over CompletionContext

**Comment by testforstephen** [comment]
> can you check if this can be resolved from the intellicode extension side with that team in away the extension will work either with or without javac changes.

The intelliCode requires some context data (e.g. `InternalCompletionContext.getCompletionNode()`) from the completion to understand the current context, and it's not exposed from parent CompletionContext.

**Comment by mickaelistria** [comment]
The getCompletionNode() isn't likely to be supported ever with javac-based JDT as it uses ECJ classes. So I'm closing it here.
On Intellisense side, some `context instanceof InternalCompletionContext ecjContext && ecjContext.isExtended()` should be added to prevent the exception.
As some other approach (such as using JDT DOM instead of ECJ) should be considered to provide further compatibility.
