### ISSUE TITLE
[JavacCompiler] compiling multiple files abort generation on 1st class with error

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#387]
In the current form, the javac used by JavacCompiler class stops generating classes whenever 1 has errors. Previous files get generated, but following ones don't get generated, even without any error in those.

I suspect a workaround is to "ungroup" the compilation code and call javac file by file. It might hurt performances though.
Another solution, probably better, is to use the `javacTask.analyze()` as it's done in JavacCompilationUnitResolver, and then to chain it output in `javacTask.generate(elements)`, which should allow to exclude content that has blocking issue.

**Comment by mickaelistria** [comment]
cc @testforstephen , something that might be interesting to you

**Comment by mickaelistria** [comment]
To reproduce, create a simple project with dummy files A.java and B.java in the source folder (no need for a package), introduce a syntax error in A.java, go click "Project > Build"
EXPECTED: B.class generated
GOT: nothing generated.

**Comment by testforstephen** [comment]
yes, this is a known issue of Javac compiler. It also happens to maven and IJ. I can take a look whether there is anything we can do to improve it.

**Comment by mickaelistria** [comment]
@testforstephen if you can look at it, that'd be great. Is this something you can plan?

**Comment by testforstephen** [comment]
In the first MVP, I will focus on the feature wise first and ensure the Javac compiler can support most project types. Since this issue is not a blocking issue, I will take it as a second step for optimization. Is there any reason you want to address it now?

**Comment by mickaelistria** [comment]
Actually, I'm wondering whether we shouldn't instead try to influence Javac directly in providing this feature (maybe we some new flag).

**Comment by testforstephen** [comment]
This issue could potentially block the incremental build process. Even after fixing all errors in the project, some files may remain uncompiled. To resolve this, I'm considering two possible approaches:

- Compile file by file: This method should address the issue, but it might cause performance problems when building large projects.
- Override specific Javac methods: This would force the build process to continue despite errors.

**Comment by mickaelistria** [comment]
> Override specific Javac methods

I think we should try it force, because if we find a way to do that, we can then try to provide this feature directly to Javac/openjdk to have an option to "generateAnyway" which could serve even more use-cases.
