### ISSUE TITLE
[javac] Weird ranges for unnecessary cast warnings

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#408]
The following code generates weird ranges :
```java
public class WeirdRange {

	Runnable getRunnable() {
		Runnable foo = (Runnable) doGetRunnable();
		return (Runnable) doGetRunnable();
	}

	Runnable doGetRunnable() {
		return null;
	}
}
```
With the equals sign and return statements being underlined:

<img width="488" alt="Screenshot 2024-05-23 at 11 39 36" src="https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/148698/eb73221a-1ac1-4f6a-aafb-f60f75eb241a">

JDT (you need to enable unnecessary cast warning) underlines the whole statement (meh):

<img width="443" alt="Screenshot 2024-05-23 at 11 39 08" src="https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/148698/e0c9b663-2073-4b36-accc-83ff03856444">

I prefer the way Intellij IDEA does it, where only the cast is highlighted:

<img width="408" alt="Screenshot 2024-05-23 at 11 39 23" src="https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/148698/6ef54211-9a5d-4057-9024-1847ab573272">

**Comment by mickaelistria** [comment]
This, and others similar cases, seem to be regressions caused by eb1f7d24b5e5de5ea04c11c6340639a039806f6b .
@datho7561 Can you please have a look? If the range given by the compiler is non-empty, does it make sense to loo at the tokens?

**Comment by datho7561** [comment]
> If the range given by the compiler is non-empty, does it make sense to loo at the tokens?

No, it doesn't make sense IMO, this is an oversight on my part, I'll take a look into this Monday.
