### ISSUE TITLE
!MESSAGE Unsupported Entry of typeclass com.sun.tools.javac.tree.JCTree$JCTypeApply

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdtls/eclipse-jdt-core-incubator#420]
!MESSAGE Unsupported Entry<IConfigurationElement, LemminxClasspathExtensionProvider> of typeclass com.sun.tools.javac.tree.JCTree$JCTypeApply

To reproduce import wildwebdeveloper projects in a workspace and rebuild.

**Comment by mickaelistria** [comment]
Fixed as part of 432816e6ba3d3cd16b8b57b858e9328737367954

**Comment by akurtakov** [comment]
Confirmed no longer seen
