### ISSUE TITLE
Run tests with javac 

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdtls/eclipse-jdt-core-incubator#425]
Making tests in the incubator branch run with javac would ensure less regressions.
Furthermore, it should fix tests running with Java 23 (at least part of the problems).
Inspired by https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3167

**Comment by mickaelistria** [comment]
I don't get it, do we want the tests running with javac or with ecj? We used to have both and ditched ECJ because we didn't care about it anymore and having the tests was making longer and harder to get feedback.

**Comment by akurtakov** [comment]
It's a typo on my side. Run with javac that is.
