### ISSUE TITLE
[Javac] Jenkins build sometimes consumes upstream JDT instead of this fork for build

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#434]
It looks like Jenkins build sometimes consumes upstream JDT instead of this fork for build, most probably when upstream has a more recent build/qualifier than the local.
The result is that is shows ~230 failures with upstream JDT vs ~2500 with the Javac-based fork.
We should try to isolate our builds a bit more from upstream.

**Comment by akurtakov** [comment]
A "hack" used in Fedora when we had builds there was to change the build qualifier from v'timestamp' to z'timestamp' that ensures that upstream builds with same version will not override.

**Comment by mickaelistria** [comment]
That would actually be nice as it would allow to more easily distinguish forked builds vs upstream ones.

**Comment by akurtakov** [comment]
It should be enough to pass `-Dtycho.buildqualifier.format='z'yyyyMMdd-HHmm` to the build.

**Comment by mickaelistria** [comment]
Cool, would you be OK submitting a PR for that?

**Comment by akurtakov** [comment]
> Cool, would you be OK submitting a PR for that?

Unfortunately, if I make the PR it won't be tested as jenkinsfile changes from non-committers are ignored.
