### ISSUE TITLE
Incremental build fails to recheck the affected classes after modifying a single class

### ISSUE THREAD

**Issue by testforstephen** [eclipse-jdtls/eclipse-jdt-core-incubator#443]
for example, when a project is imported, adding a class A to the project

```java
public class A {
    public static void method() {}
}
```

Then add class B to reference class A
```java
public class B {
       public static void method() {
             A.method();
       }
}
```

And rename `method()` in class A to `method1()`,  the incremental build is supposed to report method not found error in class B, but it does nothing.

**Comment by mickaelistria** [comment]
Could you already check whether a rebuild command is issues for B.java? Is the compiler not called, or is it called with wrong args?

**Comment by testforstephen** [comment]
To enable incremental build, the builder must maintain the reference relationship between classes. Once a class is changed, it then queries the reference table to identify the affected classes. When we switch to Javac, some class reference relationship is not updated well from the host builder AbstractImageBuilder and result in the affected classes not being recompiled.

**Comment by testforstephen** [comment]
> Could you already check whether a rebuild command is issues for B.java? Is the compiler not called, or is it called with wrong args?

For the example case, it only triggers a build for changed class A.java, no second rebuild for B.java.

**Comment by testforstephen** [comment]
Here is how the BatchImageBuilder (full build) and IncrementalImageBuilder (incremental build) work in Java Builder.

![image](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/assets/14052197/2cb9744e-8a4e-4bfb-b310-13460d5709bf)

Switching to Javac, it introduces two problems:
- **Loss of Build State**: Unlike ECJ, which is tailored for IDE tooling and preserves symbol reference data (e.g. qualifiedReferences, simpleNameReferences, rootReferences) for each compiled Java file, Javac does not return intermediate analysis data. This results in a loss of build state as described in this issue. To mitigate this, one approach is to register a task listener within the compilation task to intercept the resolved AST Tree. By traversing the AST Tree, it’s possible to regenerate reference data for each compilation unit.
- **Unable to Perform a Full Build with Compilation Errors**: Javac is unable to execute a full build when the project has compilation errors, as detailed in the issue #387. Even after fixing the erroneous code, the incremental build will only recompile affected Java files, leaving others uncompiled. As a result, probably some Java files within the project never get a chance to be compiled. This is likely a blocking issue for users.

**Comment by mickaelistria** [comment]
Would it work/help to keep the javac Context of the project and to always reuse the same context unless we have a reason to change it (eg some configuration change) ?
