### ISSUE TITLE
jdt-ls tests are flaky, often failing with `Range [0, -1) out of bounds for length 80`

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#461]
The tests failures happen each run, but the specific tests that fail change each time.

Fred first mentioned this to me.

My first lead is that the error is related to Javadoc parsing, and there is a test file called `Foo3.java` that is 81 bytes, although no files that are 80 bytes long.

**Comment by datho7561** [comment]
AbstractCompilationUnitBasedTest imports this project by default, so this class is probably loaded for many test cases.

Something worth figuring out is if the order of parsing of the files in our code is consistent. eg. if you have A.java, B.java, and C.java all loaded for parsing, and it parses, C, then A, then B, will it always do this order?

**Comment by datho7561** [comment]
I think I understand what's going on; any crash in parsing one file prevents further compilation of the next files (this is an existing bug I think Mickael mentioned). In the case of the jdt-ls tests, the Javadoc issue is causing the crash.

So the root cause is twofold:
- It might be important for the order of parsing of the files to be consistent (I don't think it is currently)
- A crash in parsing a particular file should not prevent subsequent files from being parsed.

**Comment by mickaelistria** [comment]
I think this got fixed since then.
