### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.ModuleBuilderTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#59]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
I'm on it with https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/138

**Comment by mickaelistria** [comment]
The 2 remain failures (testAutoModule3 and testAutoModule5) should be fixed with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2300

**Comment by mickaelistria** [comment]
Tests are currently ignored as upstream issue is reported and tracked, and fixing it wouldn't help for further for Javac stuff.
