### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.CompilationUnitTests*` test suites

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#60]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
https://ci.eclipse.org/ls/job/jdt-core-incubator/job/dom-based-operations/94/#showFailuresLink shows no related test failures left
