### ISSUE TITLE
private inner class with public method not reported as unused

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#630]
ECJ reports `Inner` from the following snippet as unused, whereas the analysis that we use doesn't yet report it as unused:

```java
public class HasInner {
  private static class Inner {
    public void myMethod() {
    }
  }
}
```

**Comment by testforstephen** [comment]
I cannot reproduce it with this file alone, other files might be affecting the analysis. Could you provide the full project to reproduce the issue?

**Comment by datho7561** [comment]
I'll try this again and get back to you

**Comment by datho7561** [comment]
I can't reproduce this any more! I guess it was fixed.
