### ISSUE TITLE
Handle `getKey()` for capture types

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#678]
ECJ uses a different format for the keys of wildcards and capture types. The keys for unbounded wildcards use `?`. The keys for bounded wildcards use `+` or `-` (upper vs lower bounds) and include the key of the boundary type. The keys for capture types use `!` and include a number identifier for the capture, as well as the key for the wildcard of the capture.

As far as I can tell, javac doesn't distinguish between wildcard types and capture types in the `com.sun.tools.javac.code.Type` system, its analogue of the bindings.

I personally still need to learn and understand the difference between a capture and a wildcard.

See `org.eclipse.jdt.internal.compiler.lookup.CaptureType.computeUniqueKey` for more details.

**Comment by mickaelistria** [comment]
I think it's more or less the same difference as `generic` vs `parameterized`: a wildcard is what is seen in the definition, while the capture can be how the wildcard is resolved for a reference.

**Comment by datho7561** [comment]
Apparently I missed it the first time, but there is a `Type.CapturedType` that represents type captures

**Comment by datho7561** [comment]
There might be some more edge cases to deal with, but this should be handled by #695
