### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.HierarchyOnWorkingCopiesTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#73]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
Remaining failures got fixed or ignored (if not relevant to Javac work)
