### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.ResolveTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#74]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
The **19** `testDuplicateXXX` tests highlight that in some cases, the position->DOM->binding->Java element path is erroneous because the bindings cannot resolve cases that are not supported by Javac.
When we notice such case, we can probably skip resolution and shortcut directly from position to Java element just by finding the IJavaElement that is covering the range.

**Comment by mickaelistria** [comment]
Most of the remaining testDuplicateXXX failues showing failures such as
```
junit.framework.ComparisonFailure: Unexpected type.
----------- Expected ------------
QTestString;
------------ but was ------------
Ltest/TestString;
---------------------- ----------
 expected:<[Q]TestString;> but was:<[Ltest/]TestString;>
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
	at org.eclipse.jdt.core.tests.model.ResolveTests.testDuplicateLocals1(ResolveTests.java:1469)
```
are most likely better with the failure: with bindings, the types are fully resolved (and it can be useful), while it looks like the test is used to types not being really resolved.

**Comment by mickaelistria** [comment]
This also relates to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2037 which would positively alter the output here. When https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2037 is merged, we can consider changing most tests to the form

was
```java
	assertEquals(
			"Unexpected type",
			"QTestString;",
			((ILocalVariable)elements[0]).getTypeSignature());
```
to
```java
	assertTrue(
			"Unexpected type",
			Set.of("QTestString;", "Ltest.TestString;").contains(
			((ILocalVariable)elements[0]).getTypeSignature()));
```
which would equally pass with both strategies.

**Comment by mickaelistria** [comment]
No remaining test is relevant for upcoming Javac support. All tests fixed or ignored.
