### ISSUE TITLE
ConvertForLoopOperation cannot work with Javac

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#748]
ConvertForLoopOperation uses the type of `.size()` method on collections to determine the type. While it's fine with JDT, Javac does not consider the type argument in the `.size()` method, simply because the method is always the same, so it doesn't make sense to create such separation.
The ConvertForLoopOperation could instead of this untyped `size` method check the type of the expression on which `size()` is called, and check a type method such as `add` to find the actual element type.

**Comment by akurtakov** [comment]
Is this smth for @jjohnstn to look at ?

**Comment by jjohnstn** [comment]
@mickaelistria Can this be closed now that the JDT patch has been merged?

**Comment by mickaelistria** [comment]
yes, thanks!
