### ISSUE TITLE
[javac] Improper generics usage is not properly reported

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#764]
Given:

```java
public class Test<T> {
	public static void main(String[] args) {
		Test test = new Test();
	}
}
```
The javac plugin reports no problem:
<img width="342" alt="Screenshot 2024-08-28 at 16 26 00" src="https://github.com/user-attachments/assets/7537b023-4d28-4362-8489-2aec8259265f">

while ECJ complains about generics:
<img width="762" alt="Screenshot 2024-08-28 at 16 27 45" src="https://github.com/user-attachments/assets/a1f2d4e6-4b90-4c68-bd02-7138500e0c27">

**Comment by mickaelistria** [comment]
The errors seem well reported as part of the reconcile process, however, errors from the build don't seem to be reported back as problems on the resource.

**Comment by mickaelistria** [comment]
Sorry, my last comment is incorrect. The issue was that I had "Build automatically" disabled. With build automatically turned on, I see the warnings from the reconcilers and then as markers on the resource.

**Comment by mickaelistria** [comment]
Is this still happening? I couldn't reproduce.

**Comment by mickaelistria** [comment]
Cannot reproduce
