### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.TypeHierarchyTests` test suite, as well as `TypeHierarchyNotificationTests`

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#81]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

By the name these suites look related, so I have grouped them together.

**Comment by mickaelistria** [comment]
This was seems to be entirely fixed, as no related failure is reported in https://ci.eclipse.org/ls/job/jdt-core-incubator/job/dom-based-operations/94/#showFailuresLink
