### ISSUE TITLE
[javac] Unused method parameters are not reported

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#813]
```java
public void nope(String notUsed) {
   System.err.println("Nope");
}
```

`notUsed` should be flagged as unused. It's not. Tested against latest code in master.

**Comment by testforstephen** [comment]
This is by design. Ignore unused method parameter by default, this is same behavior as ECJ compiler. You can change this behavior by turning on config `org.eclipse.jdt.core.compiler.problem.unusedParameter=warning`
