### ISSUE TITLE
File errors no longer appear

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#815]
Errors reported on the current file no longer appear. For instance, if you disable auto build and delete all the current errors, then no errors will appear in the current file as you are typing. Instead, errors

This is a result of https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/commit/cb3c54ff805b938febe42cabb52e760df1614b29#diff-824b4558baccabe7d7fbf6cd487b7f99b9b95ddd9e67fab59376483017d72dbdR483.

The PR configures a compiler for use and registers it in the `Context`, but a different instance of the compiler (https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/commit/cb3c54ff805b938febe42cabb52e760df1614b29#diff-824b4558baccabe7d7fbf6cd487b7f99b9b95ddd9e67fab59376483017d72dbdR481) is used for the compilation task. I believe the diagnostic listener gets registered on the `TolerantJavaCompiler`, which is never used.

**Comment by testforstephen** [comment]
`ToolProvider.getSystemJavaCompiler()` creates a high-level compiler interface but does not perform the actual compilation. The real compilation process requires retrieving the underlying compiler instance from the Context.

**Comment by mickaelistria** [comment]
This was fixed by reverting the culprit commit.
