### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.IgnoreOptionalProblemsFromSourceFoldersTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#84]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
Only remaining failure is caused by upstream issue https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2179

**Comment by mickaelistria** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2277 is another blocker.

**Comment by mickaelistria** [comment]
The remaining failure got ignored, as task are not provided by Javac anyway.
