### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.LocalElementTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#85]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by snjeza** [comment]
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/119, commit https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/119/commits/39cc1d8a2a2b0f39056498cf760ed74a01c93c9b fixes this test too (only testLocalType5 fails)

**Comment by mickaelistria** [comment]
All fixed or ignored.
