### ISSUE TITLE
[DOM-first] Assorted remaining tests

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#87]
Many test suites only have one or two failing tests that aren't covered in other issues. Here they are:
- org.eclipse.jdt.core.tests.model.CopyMoveElementsTests.testCopyImportStatic 
- org.eclipse.jdt.core.tests.model.ClasspathInitializerTests.testContainerInitializer06
- org.eclipse.jdt.core.tests.model.WorkingCopyOwnerTests.testNewWorkingCopy09
- org.eclipse.jdt.core.tests.model.NullAnnotationModelTests.testBug479389
- org.eclipse.jdt.core.tests.model.Java9ElementTests.test003
- org.eclipse.jdt.core.tests.model.Java9ElementTests.test530653
- org.eclipse.jdt.core.tests.model.RecordsElementTests.test005
- org.eclipse.jdt.core.tests.model.RecordsElementTests.test006

See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
> NullAnnotationModelTests.testBug479389

This one seems to fail because the ProblemHandler.policy is set to `ignoreAllErros` when using ASTParser.

**Comment by mickaelistria** [comment]
I didn't find a valid fix in some reasonable time; and the error is not relevant for future Javac work. So I have just reported https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2303 upstream and added it to the "upstream" task board, and we can close here as no further work is planned.
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/221 is the PR that ignores this failure on this branch.
