### ISSUE TITLE
Constructor completion

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#892]
eg.

```java
public class Main {
  public static void main (String... args) {
    List<String> myList = new |
  }
}
```

should complete, for example, `ArrayList<String>()` or `List<String> { ... }`.

Also:

```java
public class Main {
  public static void main (String... args) {
    new |
  }
}
```

Should suggest possible constructors. The JDT behaviour seems to only suggest local types in this case for performance reasons.

Possible roadblock: currently, the AST returned after conversion seems to turn `List<String> myList = new` into `List<String> myList;` instead of preserving the `new` by doing something like `List<String> myList = new $missing$()`.

**Comment by mickaelistria** [comment]
> Possible roadblock: currently, the AST returned after conversion seems to turn List<String> myList = new into List<String> myList; instead of preserving the new by doing something like List<String> myList = new $missing$().

What about the Tree returned by Javac? Is there some useful info we lose in translation?

**Comment by datho7561** [comment]
Yes, the info is in the javac AST. Currently, we are [explicitly preventing](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/blob/969bc5a07fb352fce857a4f954cdbdc6e8f7ec0f/org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacConverter.java#L1423) it from being added into the translated JDT AST. I have a work in progress PR that removes this and gets constructor completion (sort of) working, however this will probably cause some of the AST conversion tests to regress.

**Comment by mickaelistria** [comment]
I hope that if we guard the creation of the node with a check whether recovery is enabled, we can keep both completion and tests happy.
