### ISSUE TITLE
Error popup if a type extends itself

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#919]
eg. try creating the following class in Eclipse with javac

```java
public class HelloWorld extends HelloWorld {

}
```

There should be an error popup that you can't get rid of once you've saved this file

**Comment by datho7561** [comment]
The error is "Unhandled `Symbol` subclass class com.sun.tools.javac.code.Symtab$6", we are generating it ourselves

**Comment by datho7561** [comment]
I found a quick hack to prevent that error from occurring, but javac doesn't recover its internal bindings in that case of a cyclic inheritance tree, so lots of error popups appear.

**Comment by mickaelistria** [comment]
> javac doesn't recover its internal bindings in that case of a cyclic inheritance tree, so lots of error popups appear.

I think it's acceptable.

**Comment by datho7561** [comment]
There's still some error popups from bindings I need to address.
