### ISSUE TITLE
javac doesn't work with lombok

### ISSUE THREAD

**Issue by snjeza** [eclipse-jdtls/eclipse-jdt-core-incubator#955]
Steps to reproduce:

- start Eclipse with javac and the lombok agent
- create
```
package com.example;
import lombok.AllArgsConstructor;
import lombok.Data;
public class Main {
	public void test() {
		Person p = new Person(10, "abc");
		System.out.println(p.getAge() + p.getName());
		System.out.println(p.getAge() + p.getName());
		System.out.println(p.getAge() + p.getName());
	}
	@Data
	@AllArgsConstructor
	class Person {
		private Integer age;
		private String name;

	}
}
```
you will get seven errors and two warnings

**Comment by mickaelistria** [comment]
you don't need the lombok agent at Eclipse startup, lombok just has to be part of the classpath. Can you please try it?

**Comment by snjeza** [comment]
> you don't need the lombok agent at Eclipse startup, lombok just has to be part of the classpath. Can you please try it?

I have tried it. The issue is the same. Lombok doesn't work.
The lombok agent is required for ecj.
